#include <cassert>
#include <climits>
#include <cmath>
#include <algorithm>
#include <bitset>
#include <complex>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <iterator>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <vector>